/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/koordinator-sh/koordinator/apis/scheduling/v1alpha1"
	scheme "github.com/koordinator-sh/koordinator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DrainNodesGetter has a method to return a DrainNodeInterface.
// A group's client should implement this interface.
type DrainNodesGetter interface {
	DrainNodes() DrainNodeInterface
}

// DrainNodeInterface has methods to work with DrainNode resources.
type DrainNodeInterface interface {
	Create(ctx context.Context, drainNode *v1alpha1.DrainNode, opts v1.CreateOptions) (*v1alpha1.DrainNode, error)
	Update(ctx context.Context, drainNode *v1alpha1.DrainNode, opts v1.UpdateOptions) (*v1alpha1.DrainNode, error)
	UpdateStatus(ctx context.Context, drainNode *v1alpha1.DrainNode, opts v1.UpdateOptions) (*v1alpha1.DrainNode, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.DrainNode, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DrainNodeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DrainNode, err error)
	DrainNodeExpansion
}

// drainNodes implements DrainNodeInterface
type drainNodes struct {
	client rest.Interface
}

// newDrainNodes returns a DrainNodes
func newDrainNodes(c *SchedulingV1alpha1Client) *drainNodes {
	return &drainNodes{
		client: c.RESTClient(),
	}
}

// Get takes name of the drainNode, and returns the corresponding drainNode object, and an error if there is any.
func (c *drainNodes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DrainNode, err error) {
	result = &v1alpha1.DrainNode{}
	err = c.client.Get().
		Resource("drainnodes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DrainNodes that match those selectors.
func (c *drainNodes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DrainNodeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DrainNodeList{}
	err = c.client.Get().
		Resource("drainnodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested drainNodes.
func (c *drainNodes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("drainnodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a drainNode and creates it.  Returns the server's representation of the drainNode, and an error, if there is any.
func (c *drainNodes) Create(ctx context.Context, drainNode *v1alpha1.DrainNode, opts v1.CreateOptions) (result *v1alpha1.DrainNode, err error) {
	result = &v1alpha1.DrainNode{}
	err = c.client.Post().
		Resource("drainnodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(drainNode).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a drainNode and updates it. Returns the server's representation of the drainNode, and an error, if there is any.
func (c *drainNodes) Update(ctx context.Context, drainNode *v1alpha1.DrainNode, opts v1.UpdateOptions) (result *v1alpha1.DrainNode, err error) {
	result = &v1alpha1.DrainNode{}
	err = c.client.Put().
		Resource("drainnodes").
		Name(drainNode.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(drainNode).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *drainNodes) UpdateStatus(ctx context.Context, drainNode *v1alpha1.DrainNode, opts v1.UpdateOptions) (result *v1alpha1.DrainNode, err error) {
	result = &v1alpha1.DrainNode{}
	err = c.client.Put().
		Resource("drainnodes").
		Name(drainNode.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(drainNode).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the drainNode and deletes it. Returns an error if one occurs.
func (c *drainNodes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("drainnodes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *drainNodes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("drainnodes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched drainNode.
func (c *drainNodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DrainNode, err error) {
	result = &v1alpha1.DrainNode{}
	err = c.client.Patch(pt).
		Resource("drainnodes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
