apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    koord-app: koord-descheduler
  name: descheduler
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      koord-app: koord-descheduler
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        koord-app: koord-descheduler
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: koord-app
                      operator: In
                      values:
                        - koord-descheduler
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - args:
            - --v=4
            - --config=/config/koord-descheduler.config
          command:
            - /koord-descheduler
          image: descheduler:latest
          imagePullPolicy: Always
          name: descheduler
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: healthz
              port: 10251
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - mountPath: /config
              name: koord-descheduler-config-volume
      serviceAccountName: koord-descheduler
      terminationGracePeriodSeconds: 10
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: koord-descheduler-config
                path: koord-descheduler.config
            name: koord-descheduler-config
          name: koord-descheduler-config-volume
