/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/koordinator-sh/koordinator/apis/scheduling/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDrainNodes implements DrainNodeInterface
type FakeDrainNodes struct {
	Fake *FakeSchedulingV1alpha1
}

var drainnodesResource = schema.GroupVersionResource{Group: "scheduling.koordinator.sh", Version: "v1alpha1", Resource: "drainnodes"}

var drainnodesKind = schema.GroupVersionKind{Group: "scheduling.koordinator.sh", Version: "v1alpha1", Kind: "DrainNode"}

// Get takes name of the drainNode, and returns the corresponding drainNode object, and an error if there is any.
func (c *FakeDrainNodes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DrainNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(drainnodesResource, name), &v1alpha1.DrainNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DrainNode), err
}

// List takes label and field selectors, and returns the list of DrainNodes that match those selectors.
func (c *FakeDrainNodes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DrainNodeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(drainnodesResource, drainnodesKind, opts), &v1alpha1.DrainNodeList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DrainNodeList{ListMeta: obj.(*v1alpha1.DrainNodeList).ListMeta}
	for _, item := range obj.(*v1alpha1.DrainNodeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested drainNodes.
func (c *FakeDrainNodes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(drainnodesResource, opts))
}

// Create takes the representation of a drainNode and creates it.  Returns the server's representation of the drainNode, and an error, if there is any.
func (c *FakeDrainNodes) Create(ctx context.Context, drainNode *v1alpha1.DrainNode, opts v1.CreateOptions) (result *v1alpha1.DrainNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(drainnodesResource, drainNode), &v1alpha1.DrainNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DrainNode), err
}

// Update takes the representation of a drainNode and updates it. Returns the server's representation of the drainNode, and an error, if there is any.
func (c *FakeDrainNodes) Update(ctx context.Context, drainNode *v1alpha1.DrainNode, opts v1.UpdateOptions) (result *v1alpha1.DrainNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(drainnodesResource, drainNode), &v1alpha1.DrainNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DrainNode), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDrainNodes) UpdateStatus(ctx context.Context, drainNode *v1alpha1.DrainNode, opts v1.UpdateOptions) (*v1alpha1.DrainNode, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(drainnodesResource, "status", drainNode), &v1alpha1.DrainNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DrainNode), err
}

// Delete takes name of the drainNode and deletes it. Returns an error if one occurs.
func (c *FakeDrainNodes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(drainnodesResource, name, opts), &v1alpha1.DrainNode{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDrainNodes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(drainnodesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DrainNodeList{})
	return err
}

// Patch applies the patch and returns the patched drainNode.
func (c *FakeDrainNodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DrainNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(drainnodesResource, name, pt, data, subresources...), &v1alpha1.DrainNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DrainNode), err
}
