/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/koordinator-sh/koordinator/apis/scheduling/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeQuotaNodeBinders implements QuotaNodeBinderInterface
type FakeQuotaNodeBinders struct {
	Fake *FakeSchedulingV1alpha1
}

var quotanodebindersResource = schema.GroupVersionResource{Group: "scheduling.koordinator.sh", Version: "v1alpha1", Resource: "quotanodebinders"}

var quotanodebindersKind = schema.GroupVersionKind{Group: "scheduling.koordinator.sh", Version: "v1alpha1", Kind: "QuotaNodeBinder"}

// Get takes name of the quotaNodeBinder, and returns the corresponding quotaNodeBinder object, and an error if there is any.
func (c *FakeQuotaNodeBinders) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.QuotaNodeBinder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(quotanodebindersResource, name), &v1alpha1.QuotaNodeBinder{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QuotaNodeBinder), err
}

// List takes label and field selectors, and returns the list of QuotaNodeBinders that match those selectors.
func (c *FakeQuotaNodeBinders) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.QuotaNodeBinderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(quotanodebindersResource, quotanodebindersKind, opts), &v1alpha1.QuotaNodeBinderList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.QuotaNodeBinderList{ListMeta: obj.(*v1alpha1.QuotaNodeBinderList).ListMeta}
	for _, item := range obj.(*v1alpha1.QuotaNodeBinderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested quotaNodeBinders.
func (c *FakeQuotaNodeBinders) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(quotanodebindersResource, opts))
}

// Create takes the representation of a quotaNodeBinder and creates it.  Returns the server's representation of the quotaNodeBinder, and an error, if there is any.
func (c *FakeQuotaNodeBinders) Create(ctx context.Context, quotaNodeBinder *v1alpha1.QuotaNodeBinder, opts v1.CreateOptions) (result *v1alpha1.QuotaNodeBinder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(quotanodebindersResource, quotaNodeBinder), &v1alpha1.QuotaNodeBinder{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QuotaNodeBinder), err
}

// Update takes the representation of a quotaNodeBinder and updates it. Returns the server's representation of the quotaNodeBinder, and an error, if there is any.
func (c *FakeQuotaNodeBinders) Update(ctx context.Context, quotaNodeBinder *v1alpha1.QuotaNodeBinder, opts v1.UpdateOptions) (result *v1alpha1.QuotaNodeBinder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(quotanodebindersResource, quotaNodeBinder), &v1alpha1.QuotaNodeBinder{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QuotaNodeBinder), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeQuotaNodeBinders) UpdateStatus(ctx context.Context, quotaNodeBinder *v1alpha1.QuotaNodeBinder, opts v1.UpdateOptions) (*v1alpha1.QuotaNodeBinder, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(quotanodebindersResource, "status", quotaNodeBinder), &v1alpha1.QuotaNodeBinder{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QuotaNodeBinder), err
}

// Delete takes name of the quotaNodeBinder and deletes it. Returns an error if one occurs.
func (c *FakeQuotaNodeBinders) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(quotanodebindersResource, name), &v1alpha1.QuotaNodeBinder{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeQuotaNodeBinders) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(quotanodebindersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.QuotaNodeBinderList{})
	return err
}

// Patch applies the patch and returns the patched quotaNodeBinder.
func (c *FakeQuotaNodeBinders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.QuotaNodeBinder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(quotanodebindersResource, name, pt, data, subresources...), &v1alpha1.QuotaNodeBinder{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QuotaNodeBinder), err
}
