/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/koordinator-sh/koordinator/apis/scheduling/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDrainNodeGroups implements DrainNodeGroupInterface
type FakeDrainNodeGroups struct {
	Fake *FakeSchedulingV1alpha1
}

var drainnodegroupsResource = schema.GroupVersionResource{Group: "scheduling.koordinator.sh", Version: "v1alpha1", Resource: "drainnodegroups"}

var drainnodegroupsKind = schema.GroupVersionKind{Group: "scheduling.koordinator.sh", Version: "v1alpha1", Kind: "DrainNodeGroup"}

// Get takes name of the drainNodeGroup, and returns the corresponding drainNodeGroup object, and an error if there is any.
func (c *FakeDrainNodeGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DrainNodeGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(drainnodegroupsResource, name), &v1alpha1.DrainNodeGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DrainNodeGroup), err
}

// List takes label and field selectors, and returns the list of DrainNodeGroups that match those selectors.
func (c *FakeDrainNodeGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DrainNodeGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(drainnodegroupsResource, drainnodegroupsKind, opts), &v1alpha1.DrainNodeGroupList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DrainNodeGroupList{ListMeta: obj.(*v1alpha1.DrainNodeGroupList).ListMeta}
	for _, item := range obj.(*v1alpha1.DrainNodeGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested drainNodeGroups.
func (c *FakeDrainNodeGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(drainnodegroupsResource, opts))
}

// Create takes the representation of a drainNodeGroup and creates it.  Returns the server's representation of the drainNodeGroup, and an error, if there is any.
func (c *FakeDrainNodeGroups) Create(ctx context.Context, drainNodeGroup *v1alpha1.DrainNodeGroup, opts v1.CreateOptions) (result *v1alpha1.DrainNodeGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(drainnodegroupsResource, drainNodeGroup), &v1alpha1.DrainNodeGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DrainNodeGroup), err
}

// Update takes the representation of a drainNodeGroup and updates it. Returns the server's representation of the drainNodeGroup, and an error, if there is any.
func (c *FakeDrainNodeGroups) Update(ctx context.Context, drainNodeGroup *v1alpha1.DrainNodeGroup, opts v1.UpdateOptions) (result *v1alpha1.DrainNodeGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(drainnodegroupsResource, drainNodeGroup), &v1alpha1.DrainNodeGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DrainNodeGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDrainNodeGroups) UpdateStatus(ctx context.Context, drainNodeGroup *v1alpha1.DrainNodeGroup, opts v1.UpdateOptions) (*v1alpha1.DrainNodeGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(drainnodegroupsResource, "status", drainNodeGroup), &v1alpha1.DrainNodeGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DrainNodeGroup), err
}

// Delete takes name of the drainNodeGroup and deletes it. Returns an error if one occurs.
func (c *FakeDrainNodeGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(drainnodegroupsResource, name), &v1alpha1.DrainNodeGroup{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDrainNodeGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(drainnodegroupsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DrainNodeGroupList{})
	return err
}

// Patch applies the patch and returns the patched drainNodeGroup.
func (c *FakeDrainNodeGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DrainNodeGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(drainnodegroupsResource, name, pt, data, subresources...), &v1alpha1.DrainNodeGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DrainNodeGroup), err
}
