---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: system
  name: descheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: descheduler-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: descheduler-role
subjects:
  - kind: ServiceAccount
    name: descheduler
    namespace: system
