//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package unified

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACSSystem) DeepCopyInto(out *ACSSystem) {
	*out = *in
	if in.SchedSchedStats != nil {
		in, out := &in.SchedSchedStats, &out.SchedSchedStats
		*out = new(int64)
		**out = **in
	}
	if in.SchedAcpu != nil {
		in, out := &in.SchedAcpu, &out.SchedAcpu
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACSSystem.
func (in *ACSSystem) DeepCopy() *ACSSystem {
	if in == nil {
		return nil
	}
	out := new(ACSSystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACSSystemCfg) DeepCopyInto(out *ACSSystemCfg) {
	*out = *in
	if in.ClusterStrategy != nil {
		in, out := &in.ClusterStrategy, &out.ClusterStrategy
		*out = new(ACSSystemStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeStrategies != nil {
		in, out := &in.NodeStrategies, &out.NodeStrategies
		*out = make([]NodeACSSystemStrategy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACSSystemCfg.
func (in *ACSSystemCfg) DeepCopy() *ACSSystemCfg {
	if in == nil {
		return nil
	}
	out := new(ACSSystemCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACSSystemStrategy) DeepCopyInto(out *ACSSystemStrategy) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	in.ACSSystem.DeepCopyInto(&out.ACSSystem)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACSSystemStrategy.
func (in *ACSSystemStrategy) DeepCopy() *ACSSystemStrategy {
	if in == nil {
		return nil
	}
	out := new(ACSSystemStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUStableCfg) DeepCopyInto(out *CPUStableCfg) {
	*out = *in
	if in.ClusterStrategy != nil {
		in, out := &in.ClusterStrategy, &out.ClusterStrategy
		*out = new(CPUStableStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeStrategies != nil {
		in, out := &in.NodeStrategies, &out.NodeStrategies
		*out = make([]NodeCPUStableStrategy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUStableCfg.
func (in *CPUStableCfg) DeepCopy() *CPUStableCfg {
	if in == nil {
		return nil
	}
	out := new(CPUStableCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUStablePIDConfig) DeepCopyInto(out *CPUStablePIDConfig) {
	*out = *in
	if in.ProportionalPermill != nil {
		in, out := &in.ProportionalPermill, &out.ProportionalPermill
		*out = new(int64)
		**out = **in
	}
	if in.IntegralPermill != nil {
		in, out := &in.IntegralPermill, &out.IntegralPermill
		*out = new(int64)
		**out = **in
	}
	if in.DerivativePermill != nil {
		in, out := &in.DerivativePermill, &out.DerivativePermill
		*out = new(int64)
		**out = **in
	}
	if in.SignalNormalizedPercent != nil {
		in, out := &in.SignalNormalizedPercent, &out.SignalNormalizedPercent
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUStablePIDConfig.
func (in *CPUStablePIDConfig) DeepCopy() *CPUStablePIDConfig {
	if in == nil {
		return nil
	}
	out := new(CPUStablePIDConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUStableScaleModel) DeepCopyInto(out *CPUStableScaleModel) {
	*out = *in
	if in.TargetCPUSatisfactionPercent != nil {
		in, out := &in.TargetCPUSatisfactionPercent, &out.TargetCPUSatisfactionPercent
		*out = new(int64)
		**out = **in
	}
	if in.CPUSatisfactionEpsilonPermill != nil {
		in, out := &in.CPUSatisfactionEpsilonPermill, &out.CPUSatisfactionEpsilonPermill
		*out = new(int64)
		**out = **in
	}
	if in.HTRatioUpperBound != nil {
		in, out := &in.HTRatioUpperBound, &out.HTRatioUpperBound
		*out = new(int64)
		**out = **in
	}
	if in.HTRatioLowerBound != nil {
		in, out := &in.HTRatioLowerBound, &out.HTRatioLowerBound
		*out = new(int64)
		**out = **in
	}
	if in.CPUUtilMinPercent != nil {
		in, out := &in.CPUUtilMinPercent, &out.CPUUtilMinPercent
		*out = new(int64)
		**out = **in
	}
	if in.HTRatioIncreasePercent != nil {
		in, out := &in.HTRatioIncreasePercent, &out.HTRatioIncreasePercent
		*out = new(int64)
		**out = **in
	}
	if in.HTRatioZoomOutPercent != nil {
		in, out := &in.HTRatioZoomOutPercent, &out.HTRatioZoomOutPercent
		*out = new(int64)
		**out = **in
	}
	in.PIDConfig.DeepCopyInto(&out.PIDConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUStableScaleModel.
func (in *CPUStableScaleModel) DeepCopy() *CPUStableScaleModel {
	if in == nil {
		return nil
	}
	out := new(CPUStableScaleModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUStableStrategy) DeepCopyInto(out *CPUStableStrategy) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(CPUStablePolicy)
		**out = **in
	}
	if in.PodInitializeWindowSeconds != nil {
		in, out := &in.PodInitializeWindowSeconds, &out.PodInitializeWindowSeconds
		*out = new(int64)
		**out = **in
	}
	if in.PodMetricWindowSeconds != nil {
		in, out := &in.PodMetricWindowSeconds, &out.PodMetricWindowSeconds
		*out = new(int64)
		**out = **in
	}
	if in.ValidMetricPointsPercent != nil {
		in, out := &in.ValidMetricPointsPercent, &out.ValidMetricPointsPercent
		*out = new(int64)
		**out = **in
	}
	if in.PodDegradeWindowSeconds != nil {
		in, out := &in.PodDegradeWindowSeconds, &out.PodDegradeWindowSeconds
		*out = new(int64)
		**out = **in
	}
	in.CPUStableScaleModel.DeepCopyInto(&out.CPUStableScaleModel)
	in.WarmupConfig.DeepCopyInto(&out.WarmupConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUStableStrategy.
func (in *CPUStableStrategy) DeepCopy() *CPUStableStrategy {
	if in == nil {
		return nil
	}
	out := new(CPUStableStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUStableWarmupEntry) DeepCopyInto(out *CPUStableWarmupEntry) {
	*out = *in
	if in.SharePoolUtilPercent != nil {
		in, out := &in.SharePoolUtilPercent, &out.SharePoolUtilPercent
		*out = new(int64)
		**out = **in
	}
	if in.HTRatio != nil {
		in, out := &in.HTRatio, &out.HTRatio
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUStableWarmupEntry.
func (in *CPUStableWarmupEntry) DeepCopy() *CPUStableWarmupEntry {
	if in == nil {
		return nil
	}
	out := new(CPUStableWarmupEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUStableWarmupModel) DeepCopyInto(out *CPUStableWarmupModel) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]CPUStableWarmupEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUStableWarmupModel.
func (in *CPUStableWarmupModel) DeepCopy() *CPUStableWarmupModel {
	if in == nil {
		return nil
	}
	out := new(CPUStableWarmupModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeadlineEvictCfg) DeepCopyInto(out *DeadlineEvictCfg) {
	*out = *in
	if in.ClusterStrategy != nil {
		in, out := &in.ClusterStrategy, &out.ClusterStrategy
		*out = new(DeadlineEvictStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeStrategies != nil {
		in, out := &in.NodeStrategies, &out.NodeStrategies
		*out = make([]NodeDeadlineEvictStrategy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeadlineEvictCfg.
func (in *DeadlineEvictCfg) DeepCopy() *DeadlineEvictCfg {
	if in == nil {
		return nil
	}
	out := new(DeadlineEvictCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeadlineEvictConfig) DeepCopyInto(out *DeadlineEvictConfig) {
	*out = *in
	if in.DeadlineDuration != nil {
		in, out := &in.DeadlineDuration, &out.DeadlineDuration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeadlineEvictConfig.
func (in *DeadlineEvictConfig) DeepCopy() *DeadlineEvictConfig {
	if in == nil {
		return nil
	}
	out := new(DeadlineEvictConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeadlineEvictStrategy) DeepCopyInto(out *DeadlineEvictStrategy) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	in.DeadlineEvictConfig.DeepCopyInto(&out.DeadlineEvictConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeadlineEvictStrategy.
func (in *DeadlineEvictStrategy) DeepCopy() *DeadlineEvictStrategy {
	if in == nil {
		return nil
	}
	out := new(DeadlineEvictStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicProdResourceConfig) DeepCopyInto(out *DynamicProdResourceConfig) {
	*out = *in
	if in.ProdOvercommitPolicy != nil {
		in, out := &in.ProdOvercommitPolicy, &out.ProdOvercommitPolicy
		*out = new(ProdOvercommitPolicy)
		**out = **in
	}
	if in.ProdCPUOvercommitDefaultPercent != nil {
		in, out := &in.ProdCPUOvercommitDefaultPercent, &out.ProdCPUOvercommitDefaultPercent
		*out = new(int64)
		**out = **in
	}
	if in.ProdCPUOvercommitMaxPercent != nil {
		in, out := &in.ProdCPUOvercommitMaxPercent, &out.ProdCPUOvercommitMaxPercent
		*out = new(int64)
		**out = **in
	}
	if in.ProdCPUOvercommitMinPercent != nil {
		in, out := &in.ProdCPUOvercommitMinPercent, &out.ProdCPUOvercommitMinPercent
		*out = new(int64)
		**out = **in
	}
	if in.ProdMemoryOvercommitDefaultPercent != nil {
		in, out := &in.ProdMemoryOvercommitDefaultPercent, &out.ProdMemoryOvercommitDefaultPercent
		*out = new(int64)
		**out = **in
	}
	if in.ProdMemoryOvercommitMaxPercent != nil {
		in, out := &in.ProdMemoryOvercommitMaxPercent, &out.ProdMemoryOvercommitMaxPercent
		*out = new(int64)
		**out = **in
	}
	if in.ProdMemoryOvercommitMinPercent != nil {
		in, out := &in.ProdMemoryOvercommitMinPercent, &out.ProdMemoryOvercommitMinPercent
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicProdResourceConfig.
func (in *DynamicProdResourceConfig) DeepCopy() *DynamicProdResourceConfig {
	if in == nil {
		return nil
	}
	out := new(DynamicProdResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeACSSystemStrategy) DeepCopyInto(out *NodeACSSystemStrategy) {
	*out = *in
	in.NodeCfgProfile.DeepCopyInto(&out.NodeCfgProfile)
	if in.ACSSystemStrategy != nil {
		in, out := &in.ACSSystemStrategy, &out.ACSSystemStrategy
		*out = new(ACSSystemStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeACSSystemStrategy.
func (in *NodeACSSystemStrategy) DeepCopy() *NodeACSSystemStrategy {
	if in == nil {
		return nil
	}
	out := new(NodeACSSystemStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCPUStableStrategy) DeepCopyInto(out *NodeCPUStableStrategy) {
	*out = *in
	in.NodeCfgProfile.DeepCopyInto(&out.NodeCfgProfile)
	if in.CPUStableStrategy != nil {
		in, out := &in.CPUStableStrategy, &out.CPUStableStrategy
		*out = new(CPUStableStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCPUStableStrategy.
func (in *NodeCPUStableStrategy) DeepCopy() *NodeCPUStableStrategy {
	if in == nil {
		return nil
	}
	out := new(NodeCPUStableStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDeadlineEvictStrategy) DeepCopyInto(out *NodeDeadlineEvictStrategy) {
	*out = *in
	in.NodeCfgProfile.DeepCopyInto(&out.NodeCfgProfile)
	if in.DeadlineEvictStrategy != nil {
		in, out := &in.DeadlineEvictStrategy, &out.DeadlineEvictStrategy
		*out = new(DeadlineEvictStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDeadlineEvictStrategy.
func (in *NodeDeadlineEvictStrategy) DeepCopy() *NodeDeadlineEvictStrategy {
	if in == nil {
		return nil
	}
	out := new(NodeDeadlineEvictStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDynamicProdConfig) DeepCopyInto(out *NodeDynamicProdConfig) {
	*out = *in
	in.DynamicProdResourceConfig.DeepCopyInto(&out.DynamicProdResourceConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDynamicProdConfig.
func (in *NodeDynamicProdConfig) DeepCopy() *NodeDynamicProdConfig {
	if in == nil {
		return nil
	}
	out := new(NodeDynamicProdConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCPUStableStrategy) DeepCopyInto(out *PodCPUStableStrategy) {
	*out = *in
	in.CPUStableStrategy.DeepCopyInto(&out.CPUStableStrategy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCPUStableStrategy.
func (in *PodCPUStableStrategy) DeepCopy() *PodCPUStableStrategy {
	if in == nil {
		return nil
	}
	out := new(PodCPUStableStrategy)
	in.DeepCopyInto(out)
	return out
}
