apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnstack-koord-scheduler-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.koordinator.sh
  - slo.koordinator.sh
  - scheduling.koordinator.sh
  - topology.node.k8s.io
  - scheduling.sigs.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - networking.alibaba.com
  - csi.aliyun.com
  - snapshot.storage.k8s.io
  resources:
  - '*'
  verbs:
  - '*'